apiVersion: v1
kind: ServiceAccount
metadata:
  name: docker-agent-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: docker-agent-cr
rules:
- apiGroups: ["tool.6zacode-toolbox.github.io"]
  resources: ["dockerhosts", "dockerhosts/status"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: docker-agent-crb
subjects:
- kind: ServiceAccount
  name: docker-agent-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: docker-agent-cr
  apiGroup: rbac.authorization.k8s.io