{{ if .Values.useExternalSecret }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: docker-secret
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  target:
    name: docker-secret
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secrets-backend
  refreshInterval: 10s
  dataFrom:
    - extract:      
        key: /docker-certs
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-secret
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  target:
    name: github
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secrets-backend
  refreshInterval: 10s
  data:
    - secretKey: GITHUB_TOKEN
      remoteRef:
        key: /ci-secrets        
        property: PERSONAL_ACCESS_TOKEN
{{ end }}        