apiVersion: tool.6zacode-toolbox.github.io/v1
kind: DockerComposeRunner
metadata:
  labels:
    app.kubernetes.io/name: dockercomposerunner
    app.kubernetes.io/instance: dockercomposerunner-sample
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: dockercomposerunner-sample
spec:
  # TODO(user): Add fields here
  resourceOwner: dockerhost-sample  
  composeFile: docker-compose.yaml
  repoAddress: github.com/6zacode-toolbox/docker-compose-demo.git